version: '3.8'
services:

  flyway:
    image: flyway/flyway
    container_name: flyway
    environment:
      SQL_USER: ${SQL_USER}
      SQL_PASS: ${SQL_PASS}
      SQL_DATABASE: ${SQL_DATABASE}
    command: migrate
    volumes:
      - ./flyway/conf:/flyway/conf
      - ./flyway/sql:/flyway/sql
    networks:
      - sql_network
    depends_on:
      - database
  
networks:
  sql_network:
    external: true
