version: "3.8"

services:
  database:
    image: mysql
    container_name: database
    restart: always
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_PASS}
      MYSQL_DATABASE: ${SQL_DATABASE}
    ports:
      - ${SQL_PORT}:3306
    networks:
      - sql_network

networks:
  sql_network:
    external: true